#! /bin/bash
shopt -s extglob
declare -a array=()
read -p "How many elements do you want to enter? " inpnum
if [[ $inpnum =~ ^([0-9]) ]]; then
	typeset -i i=0
	while (( $i < $inpnum ))
	do
		read -p $((++i))": " element
		array+=($element)
	done
	typeset -i sum=0
	for num in "${array[@]}"
	do
		(( sum+=$num ))
	done
	declare -i size=${#array[@]}
	echo "Average = "$(($sum/$size))
else
	echo "Not Number"
fi


