#! /bin/bash

if [[ $# = 0 ]]; then
	ls .
else
	declare options=""
	declare args=""
	for varb in "$@"
	do
		if [[ ${varb:0:1} = "-" ]]; then
			declare sngloption=$(echo $varb | cut -c 2-)
			options+=$sngloption
		else
			if [[ $args = "" ]]; then
				args+=$varb
			else
				args+=" "$varb
			fi
		fi
	done
	declare -i flag=1
	for (( i=0; i<${#options}; i++ )); do
		if [[ ${options:$i:1} != "l" && ${options:$i:1} != "R" && ${options:$i:1} != "i" && ${options:$i:1} != "a" && ${options:$i:1} != "d" ]]; then
			printf ${options:$i:1}
			flag=0
		fi
	done
	if [[ flag -eq 1 ]]; then
		ls "-"$options $args
	else
		printf "\nInvalid Options\n"
	fi
	
fi
